### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by bk2204** [opendevise/presentation-bespoke-starter#2]
It would be great if you could add a license to this repository. I'd like to use it as a base for a talk I'm giving, but I want to provide the source to my slides.  Pretty much any standard open-source license would meet my needs, as would CC0, if you'd prefer that.

**Comment by mojavelinux** [comment]
Oops! I forgot to add a license (and I missed the notification for this issue). Adding one right now.

**Comment by mojavelinux** [comment]
License added! Thanks again for pointing this out.
