### ISSUE TITLE
Enable generation of bigger html files

### ISSUE THREAD

**Issue by hasalex** [opendevise/presentation-bespoke-starter#6]
The usage of gulp-exec limits the size of the generated html file. 
When the file is too big, I get an error "stdout maxBuffer exceeded". According to [this issue](https://github.com/robrich/gulp-exec/issues/27), it occurs at 200 kB. This size can be easily reached if I inline SVG images.

**Comment by mojavelinux** [comment]
I didn't realize that. Is there a way to increase buffer size?

**Comment by hasalex** [comment]
It calls child_process.exec, and according to its [documentation](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback), yes we can set the maxBuffer option:
`exec('bundle exec asciidoctor-bespoke -o - src/index.adoc', { pipeStdout: true, maxBuffer: 2000*1024 })`

**Comment by mojavelinux** [comment]
Let's do it! Want to send a PR?

**Comment by hasalex** [comment]
Done: PR #8

**Comment by mojavelinux** [comment]
I don't get this error, which tells me the default must differ by platform (or perhaps version of node gulp-exec or node). I'm still fine with setting it explicitly, just pointing out that I just generated a 2.3GB HTML file and it didn't fail (though it took 5min and all my CPU).

**Comment by mojavelinux** [comment]
Nevermind, I see the difference. I was using child_process in my project, not gulp-exec.

**Comment by mojavelinux** [comment]
I decided to make 100MiB the default value. This will also solve problems if you data-uri to embed binary images.

**Comment by mojavelinux** [comment]
Thanks!
