### ISSUE TITLE
Add the page number on each slide

### ISSUE THREAD

**Issue by hasalex** [opendevise/presentation-bespoke-starter#9]
I would like to add a footer on my slides with some information like a copyright and the page number.

I know that it's not a good practice for a presentation, but I need it for a course slidedeck.

I have a solution with a homemade module, and I wanted to know if BespokeJS / Asciidoctor provide something out of the box.

**Comment by mojavelinux** [comment]
My recommendation here is to use CSS. You can see this implemented in the Bespoke emulating Shower demo. See https://github.com/opendevise/bespoke-emulating-shower.

**Comment by hasalex** [comment]
I've just learned the counter feature in CSS. It's working fine for the page number.

When comparing to the JS way, here are the pros and cons of CSS:
**Pros**: lightweight, elegant, none intrusive
**Cons**: limited to simple content

**Comment by hasalex** [comment]
Here is my footer with two independant parts...

The page number:
```
section:after
  counter-increment page-number 
  content counter(page-number)
  position absolute
  bottom 1rem
  right 2rem
  font-size 1.3rem
  text-align right 
```

The text part:
```
section:before
  content "bla bla"
  position absolute
  bottom 1rem
  left 2rem
  font-size 1rem
```

**Comment by mojavelinux** [comment]
It is limited to simple content, but you'd be surprised how far that can be stretched. For instance, I use it to number the hacks in my brain hacks talk. See https://mojavelinux.github.io/presentation-write-more-fluently. 

Keep in mind the other thing you can do is use JavaScript to resolve and add content to a data attribute that CSS then displays. Then, you virtually eliminate any limitations.

Perhaps we should add this tip to the README. WDYT?

**Comment by hasalex** [comment]
The best advice that you could add is "Learn CSS".

Othervise, the best place for such a tip would be in a better BespokeJS documentation.
